// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for macOS - '
          'use FirebaseOptions directly',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for Windows - '
          'use FirebaseOptions directly',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for Linux - '
          'use FirebaseOptions directly',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-WEB-API-KEY', // Replace with your actual API key
    appId: 'YOUR-WEB-APP-ID', // Replace with your actual App ID
    messagingSenderId: 'YOUR-SENDER-ID', // Replace with your actual Sender ID
    projectId: 'olofoofo-f4a3a', // Your project ID
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    authDomain: 'olofoofo-f4a3a.firebaseapp.com', // Your auth domain
    storageBucket: 'olofoofo-f4a3a.appspot.com', // Your storage bucket
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-ANDROID-API-KEY', // Replace with your actual API key
    appId: 'YOUR-ANDROID-APP-ID', // Replace with your actual App ID
    messagingSenderId: 'YOUR-SENDER-ID', // Replace with your actual Sender ID
    projectId: 'olofoofo-f4a3a', // Your project ID
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    storageBucket: 'olofoofo-f4a3a.appspot.com', // Your storage bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY', // Replace with your actual API key
    appId: 'YOUR-IOS-APP-ID', // Replace with your actual App ID
    messagingSenderId: 'YOUR-SENDER-ID', // Replace with your actual Sender ID
    projectId: 'olofoofo-f4a3a', // Your project ID
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    storageBucket: 'olofoofo-f4a3a.appspot.com', // Your storage bucket
    iosBundleId: 'com.example.olofoofoProject', // Your iOS bundle ID
  );
}
