// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdDls0TIzYZszgwmIAlcyIUGvaEET-h8Y',
    appId: '1:441749491686:web:bda176dcc824988a18d027',
    messagingSenderId: '441749491686',
    projectId: 'olofoofo-f4a3a',
    authDomain: 'olofoofo-f4a3a.firebaseapp.com',
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    storageBucket: 'olofoofo-f4a3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdDls0TIzYZszgwmIAlcyIUGvaEET-h8Y',
    appId: '1:441749491686:android:cad8e7b2d0aee75418d027',
    messagingSenderId: '441749491686',
    projectId: 'olofoofo-f4a3a',
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    storageBucket: 'olofoofo-f4a3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDls0TIzYZszgwmIAlcyIUGvaEET-h8Y',
    appId: '1:441749491686:ios:114eee7b4844295418d027',
    messagingSenderId: '441749491686',
    projectId: 'olofoofo-f4a3a',
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    storageBucket: 'olofoofo-f4a3a.appspot.com',
    iosClientId:
        '441749491686-4qgbsv5tqjf8ib8qqoqbqq6ld5jtf8q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.olofoofoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDls0TIzYZszgwmIAlcyIUGvaEET-h8Y',
    appId: '1:441749491686:ios:114eee7b4844295418d027',
    messagingSenderId: '441749491686',
    projectId: 'olofoofo-f4a3a',
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    storageBucket: 'olofoofo-f4a3a.appspot.com',
    iosClientId:
        '441749491686-4qgbsv5tqjf8ib8qqoqbqq6ld5jtf8q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.olofoofoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdDls0TIzYZszgwmIAlcyIUGvaEET-h8Y',
    appId: '1:441749491686:web:124e9507311e711118d027',
    messagingSenderId: '441749491686',
    projectId: 'olofoofo-f4a3a',
    databaseURL: 'https://olofoofo-f4a3a-default-rtdb.firebaseio.com',
    storageBucket: 'olofoofo-f4a3a.appspot.com',
    authDomain: 'olofoofo-f4a3a.firebaseapp.com',
  );
}
